#!/bin/bash

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

printf "🚔    Linting with Rubocop...\n"

bin/bundle exec rubocop -v >/dev/null 2>&1 || { 
  printf "${CLEAR_LINE}💀${RED}   Install Rubocop and be sure it is available on your PATH${NO_COLOR}\n"
  printf "ℹ️   Try 'gem install rubocop'\n"
  exit -1
}

suspects="$(git diff --cached --name-only --diff-filter=AMC | grep "\.rb$" | tr '\n' ' ')"

if [ -n "$suspects" ]; then
  if [ ! -f '.rubocop.yml' ]; then
    printf "${CLEAR_LINE}${YELLOW}⚠️   No .rubocop.yml config file.${NO_COLOR}\n"
  fi

  printf "${CLEAR_LINE}🚔   Linting files: ${suspects}"

  # Run rubocop on the staged files
  if ! bin/bundle exec rubocop --parallel --format simple ${suspects} > /dev/null
  then
    printf "${CLEAR_LINE}${RED}💀   Rubocop found some issues. Fix, stage, and commit again${NO_COLOR}\n"
    printf "ℹ️   Try 'bin/bundle exec rubocop --display-cop-names --extra-details --auto-correct && git add -p'\n"
    exit -1
  fi
fi

printf "${CLEAR_LINE}🎉${GREEN}   Rubocop is appeased.${NO_COLOR}\n"
exit 0
